# Generated by Django 3.2.7 on 2024-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='icon',
            field=models.CharField(default='fas fa-book-open', max_length=50),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rpe',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
