# Generated by Django 3.2.7 on 2024-07-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20240724_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='area',
            new_name='area_trabajo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_empleado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='area_adscripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='categoria_descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='descripcion_categoria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_antiguedad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tc',
            field=models.CharField(default=6, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
