# Generated by Django 3.2.7 on 2024-07-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_auto_20240725_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='contenido',
            field=models.FileField(blank=True, null=True, upload_to='cursos/contenidos/'),
        ),
    ]
