# Generated by Django 3.2.7 on 2024-07-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_curso_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
