# Generated by Django 3.2.7 on 2024-07-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_auto_20240729_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_estudiantes/'),
        ),
    ]
