# Generated by Django 3.2.7 on 2024-07-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_auto_20240731_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaadscripcion',
            name='clave',
        ),
        migrations.AddField(
            model_name='areaadscripcion',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areaadscripcion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
