# Generated by Django 3.2.7 on 2024-08-01 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_auto_20240731_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area_adscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.areaadscripcion'),
        ),
    ]
