# Generated by Django 3.2.7 on 2024-08-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_alter_usuario_area_adscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='aprobado_diploma',
            field=models.BooleanField(default=False),
        ),
    ]
