# Generated by Django 3.2.7 on 2024-08-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_matricula_aprobado_diploma'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='plantilla_diploma',
            field=models.FileField(blank=True, null=True, upload_to='plantillas_diplomas/'),
        ),
    ]
