# Generated by Django 3.2.7 on 2024-08-02 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_curso_plantilla_diploma'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='diploma_archivo',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/'),
        ),
        migrations.CreateModel(
            name='DiplomaFirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='diplomas/firmados/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
